apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-app-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: uber-app
  template:
    metadata:
      labels:
        app: uber-app
    spec:
      containers:
      - name: uber-app
        image: yash5090/uber-app:latest
        ports:
        - containerPort: 5000
